### ISSUE TITLE
Implement -m switch for rafind

### ISSUE THREAD

**Issue by oddcoder** [Rair-Project/rair-core#1]
-m is magic search, file-type carver similar to `rafind2 -m` from radare2 repo

**Comment by TsarFox** [comment]
Mind if I claim this one?

**Comment by trufae** [comment]
All yours. Nobody is touching this project for a long time

**Comment by TsarFox** [comment]
Ah, I saw a few commits from two days ago and thought that activity was starting up again.

**Comment by trufae** [comment]
Oh i see, didnt knew that. I guess you can take it, but for now, only @oddcoder is in charge

**Comment by oddcoder** [comment]
Hi, yes project is staring again in silence, didn't expect anyone to notice
haha, but I would advice against wasting your time on any of the current
issues at the time being. All the current issues are in the wrong
direction, and I even killed rafind. Just because I started 2 few days ago,
didn't have time to update issues. But I will very soon.
