### ISSUE TITLE
rair can not open empty files

### ISSUE THREAD

**Issue by gogo2464** [Rair-Project/rair-core#83]
Rair can not open empty files:

> Unrecoverable Error: memory map must have a non-zero length
> Exiting!

Radare2 does not have this issue.

**Comment by oddcoder** [comment]
well I am not sure if there is use case where you will need to open a file of zero length. Please note that rair cannot append to files so opening empty file shouldn't be of any use to start with. 

if you want to open an empty file (empty as in fully zeroed memory) you can try something like
```
rair -p rw malloc://512
```

**Comment by ITAYC0HEN** [comment]
opening rair in a playground mode (e.g with rw mallocated memory) can be very useful

**Comment by oddcoder** [comment]
@ITAYC0HEN you can actually do even better you can open file with with rw copy on write memory for any and all patch attempts without touching the file on disk

`rair -p c /bin/ls`  where `c` for Copy on write.
