### ISSUE TITLE
SIMD-accelerated Levenshtein/restricted Damerau-Levenshtein distance/etc.

### ISSUE THREAD

**Issue by Daniel-Liu-c0deb0t** [Rair-Project/rair-core#88]
Hello, I was looking through BK-tree implementations and I found your rtrees library. I am working on efficient edit distance calculations through SIMD in my library [here](https://crates.io/crates/triple_accel/), and I was wondering whether you were interested in adding some additional edit distance metrics for the BK-tree implementation. I think it would be an interesting addition, and I would be willing to work on a pull request.

**Comment by oddcoder** [comment]
Hello, That would very nice addition, feel free to do so!
looking forward for your pull request.

**Comment by Daniel-Liu-c0deb0t** [comment]
I am a bit busy right now, but I will do a PR soon. I am curious: how is rtrees used in RAIR? I am familiar with the trees, but not with the overall project that they seem to be part of.

**Comment by oddcoder** [comment]
The Augmented RBtree itself  is not directly used, but it is used to create interval search tree. IST is used as data structure for memory regions mapping / unmapping. The BKTree is used to create fuzzy search for commands as in the screenshot
![image](https://user-images.githubusercontent.com/10424605/84143957-bbed7700-aa57-11ea-95f3-831857cbc6cb.png)

**Comment by Daniel-Liu-c0deb0t** [comment]
I see, thank you for the explanation!
